states_info = {
    "AL": {"state_name": "Alabama", "region": "Southeast"},
    "AK": {"state_name": "Alaska", "region": "West"},
    "AZ": {"state_name": "Arizona", "region": "Southwest"},
    "AR": {"state_name": "Arkansas", "region": "Southeast"},
    "CA": {"state_name": "California", "region": "West"},
    "CO": {"state_name": "Colorado", "region": "West"},
    "CT": {"state_name": "Connecticut", "region": "Northeast"},
    "DE": {"state_name": "Delaware", "region": "Northeast"},
    "FL": {"state_name": "Florida", "region": "Southeast"},
    "GA": {"state_name": "Georgia", "region": "Southeast"},
    "HI": {"state_name": "Hawaii", "region": "West"},
    "ID": {"state_name": "Idaho", "region": "West"},
    "IL": {"state_name": "Illinois", "region": "Midwest"},
    "IN": {"state_name": "Indiana", "region": "Midwest"},
    "IA": {"state_name": "Iowa", "region": "Midwest"},
    "KS": {"state_name": "Kansas", "region": "Midwest"},
    "KY": {"state_name": "Kentucky", "region": "Southeast"},
    "LA": {"state_name": "Louisiana", "region": "Southeast"},
    "ME": {"state_name": "Maine", "region": "Northeast"},
    "MD": {"state_name": "Maryland", "region": "Northeast"},
    "MA": {"state_name": "Massachusetts", "region": "Northeast"},
    "MI": {"state_name": "Michigan", "region": "Midwest"},
    "MN": {"state_name": "Minnesota", "region": "Midwest"},
    "MS": {"state_name": "Mississippi", "region": "Southeast"},
    "MO": {"state_name": "Missouri", "region": "Midwest"},
    "MT": {"state_name": "Montana", "region": "West"},
    "NE": {"state_name": "Nebraska", "region": "Midwest"},
    "NV": {"state_name": "Nevada", "region": "West"},
    "NH": {"state_name": "New Hampshire", "region": "Northeast"},
    "NJ": {"state_name": "New Jersey", "region": "Northeast"},
    "NM": {"state_name": "New Mexico", "region": "Southwest"},
    "NY": {"state_name": "New York", "region": "Northeast"},
    "NC": {"state_name": "North Carolina", "region": "Southeast"},
    "ND": {"state_name": "North Dakota", "region": "Midwest"},
    "OH": {"state_name": "Ohio", "region": "Midwest"},
    "OK": {"state_name": "Oklahoma", "region": "Southwest"},
    "OR": {"state_name": "Oregon", "region": "West"},
    "PA": {"state_name": "Pennsylvania", "region": "Northeast"},
    "RI": {"state_name": "Rhode Island", "region": "Northeast"},
    "SC": {"state_name": "South Carolina", "region": "Southeast"},
    "SD": {"state_name": "South Dakota", "region": "Midwest"},
    "TN": {"state_name": "Tennessee", "region": "Southeast"},
    "TX": {"state_name": "Texas", "region": "Southwest"},
    "UT": {"state_name": "Utah", "region": "West"},
    "VT": {"state_name": "Vermont", "region": "Northeast"},
    "VA": {"state_name": "Virginia", "region": "Southeast"},
    "WA": {"state_name": "Washington", "region": "West"},
    "WV": {"state_name": "West Virginia", "region": "Southeast"},
    "WI": {"state_name": "Wisconsin", "region": "Midwest"},
    "WY": {"state_name": "Wyoming", "region": "West"}
}